# Generated by Django 4.2.7 on 2023-11-10 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Salas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('nome_reserva', models.CharField(max_length=100)),
                ('data_reserva', models.DateField(max_length=30)),
                ('data_devolucao', models.DateField(max_length=30)),
            ],
        ),
    ]
