# Generated by Django 4.2.7 on 2023-11-10 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sala', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salas',
            options={'verbose_name': 'Sala'},
        ),
        migrations.RenameField(
            model_name='salas',
            old_name='nome_reserva',
            new_name='sala',
        ),
        migrations.AlterField(
            model_name='salas',
            name='data_devolucao',
            field=models.DateTimeField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='salas',
            name='data_reserva',
            field=models.DateTimeField(max_length=30),
        ),
        migrations.AlterField(
            model_name='salas',
            name='nome',
            field=models.CharField(max_length=100),
        ),
    ]
