# Generated by Django 4.2.7 on 2023-11-10 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sala', '0002_alter_salas_options_rename_nome_reserva_salas_sala_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salas',
            name='data_devolucao',
        ),
        migrations.RemoveField(
            model_name='salas',
            name='data_reserva',
        ),
        migrations.RemoveField(
            model_name='salas',
            name='nome',
        ),
    ]
