# Generated by Django 4.2.7 on 2023-11-10 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sala', '0004_rename_sala_salas_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='salas',
            name='local',
            field=models.CharField(choices=[('UABJ', 'UABJ'), ('AEB', 'AEB')], default='UABJ', max_length=4),
        ),
    ]
