# Generated by Django 4.2.7 on 2023-11-10 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sala', '0006_reserva'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reserva',
            new_name='Reservas',
        ),
    ]
